-- Execute this in Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists registrations (
  id uuid primary key default gen_random_uuid(),
  "fullName" text not null,
  cpf text not null,
  cns text,
  phone text,
  "birthDate" text not null,
  "legalGuardian" text,
  cep text,
  logradouro text,
  bairro text,
  cidade text,
  estado text,
  "documentFileId" uuid,
  "proofOfResidenceFileId" uuid,
  "proofOfResidenceDate" text,
  "medicalReportFileId" uuid,
  "medicalReportDate" text,
  cid text,
  "justificativaCid" text,
  crm text,
  "photoFileId" uuid,
  "issueDate" text not null,
  "expiryDate" text not null,
  status text not null default 'under_review',
  "visualSignature" text,
  checksum text,
  "userId" text,
  "photoUrl" text,
  "documentUrl" text,
  "proofOfResidenceUrl" text,
  "medicalReportUrl" text,
  created_at timestamptz not null default now()
);

create table if not exists registration_index (
  cpf text primary key,
  registration_id uuid not null references registrations(id) on delete cascade,
  status text not null default 'under_review',
  updated_at timestamptz not null default now()
);

create table if not exists public_validations (
  id uuid primary key references registrations(id) on delete cascade,
  "fullName" text not null,
  "cpfMasked" text not null,
  "issueDate" text not null,
  "expiryDate" text not null,
  status text not null default 'under_review',
  "visualSignature" text not null,
  checksum text
);

create table if not exists cipf_files (
  id uuid primary key default gen_random_uuid(),
  type text not null,
  name text not null,
  data text,
  total_chunks int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists cipf_file_chunks (
  file_id uuid not null references cipf_files(id) on delete cascade,
  chunk_index int not null,
  data text not null,
  primary key(file_id, chunk_index)
);

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  "registrationId" uuid,
  "userId" text,
  "userName" text,
  ip text,
  timestamp timestamptz not null default now(),
  action text not null,
  reason text
);

create index if not exists idx_registrations_cpf on registrations(cpf);
create index if not exists idx_registrations_status on registrations(status);
create index if not exists idx_logs_registration_id on audit_logs("registrationId");
create index if not exists idx_public_validations_status on public_validations(status);
create index if not exists idx_public_validations_signature on public_validations("visualSignature");

create or replace function public.validate_cipf(p_id uuid, p_sig text)
returns table (
  id uuid,
  "fullName" text,
  "cpfMasked" text,
  "issueDate" text,
  "expiryDate" text,
  status text,
  "visualSignature" text,
  checksum text
)
language sql
stable
security definer
set search_path = public
as $$
  select
    pv.id,
    pv."fullName",
    pv."cpfMasked",
    pv."issueDate",
    pv."expiryDate",
    pv.status,
    pv."visualSignature",
    pv.checksum
  from public.public_validations pv
  where pv.id = p_id
    and upper(trim(pv."visualSignature")) = upper(trim(p_sig))
  limit 1;
$$;

revoke all on function public.validate_cipf(uuid, text) from public;
grant execute on function public.validate_cipf(uuid, text) to anon, authenticated;

alter table registrations enable row level security;
alter table registration_index enable row level security;
alter table public_validations enable row level security;
alter table cipf_files enable row level security;
alter table cipf_file_chunks enable row level security;
alter table audit_logs enable row level security;

drop policy if exists all_registrations on registrations;
drop policy if exists all_registration_index on registration_index;
drop policy if exists read_public_validations on public_validations;
drop policy if exists all_cipf_files on cipf_files;
drop policy if exists all_cipf_file_chunks on cipf_file_chunks;
drop policy if exists all_audit_logs on audit_logs;

-- MVP policy set (uses anon key). You can harden this later with auth roles.
create policy all_registrations on registrations for all to anon using (true) with check (true);
create policy all_registration_index on registration_index for all to anon using (true) with check (true);
create policy read_public_validations on public_validations for all to anon using (true) with check (true);
create policy all_cipf_files on cipf_files for all to anon using (true) with check (true);
create policy all_cipf_file_chunks on cipf_file_chunks for all to anon using (true) with check (true);
create policy all_audit_logs on audit_logs for all to anon using (true) with check (true);
