-- Execute this in Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists registrations (
  id uuid primary key default gen_random_uuid(),
  "fullName" text not null,
  cpf text not null,
  cns text,
  phone text,
  "birthDate" text not null,
  "legalGuardian" text,
  cep text,
  logradouro text,
  bairro text,
  cidade text,
  estado text,
  "documentFileId" uuid,
  "proofOfResidenceFileId" uuid,
  "proofOfResidenceDate" text,
  "medicalReportFileId" uuid,
  "medicalReportDate" text,
  cid text,
  "justificativaCid" text,
  crm text,
  "photoFileId" uuid,
  "issueDate" text not null,
  "expiryDate" text not null,
  status text not null default 'under_review',
  "visualSignature" text,
  checksum text,
  "userId" text,
  "photoUrl" text,
  "documentUrl" text,
  "proofOfResidenceUrl" text,
  "medicalReportUrl" text,
  patient_notified_at timestamptz,
  patient_notified_by text,
  patient_notification_channel text,
  picked_up_at timestamptz,
  picked_up_by text,
  pickup_note text,
  last_accessed_at timestamptz,
  last_accessed_by text,
  deleted_at timestamptz,
  deleted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists registration_index (
  cpf text primary key,
  registration_id uuid not null references registrations(id) on delete cascade,
  status text not null default 'under_review',
  updated_at timestamptz not null default now()
);

create table if not exists public_validations (
  id uuid primary key references registrations(id) on delete cascade,
  "fullName" text not null,
  "cpfMasked" text not null,
  "issueDate" text not null,
  "expiryDate" text not null,
  status text not null default 'under_review',
  "visualSignature" text not null,
  checksum text,
  deleted_at timestamptz
);

create table if not exists cipf_files (
  id uuid primary key default gen_random_uuid(),
  type text not null,
  name text not null,
  data text,
  total_chunks int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists cipf_file_chunks (
  file_id uuid not null references cipf_files(id) on delete cascade,
  chunk_index int not null,
  data text not null,
  primary key(file_id, chunk_index)
);

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  "registrationId" uuid,
  "userId" text,
  "userName" text,
  ip text,
  timestamp timestamptz not null default now(),
  action text not null,
  reason text,
  event_code text,
  category text check (category in ('auth', 'registration', 'workflow', 'document', 'export', 'system')),
  severity text check (severity in ('info', 'warning', 'sensitive')),
  target_type text check (target_type in ('registration', 'system', 'file', 'session')),
  target_id uuid,
  target_label text,
  summary text,
  details text,
  metadata_json jsonb not null default '{}'::jsonb
);

alter table audit_logs add column if not exists event_code text;
alter table audit_logs add column if not exists category text;
alter table audit_logs add column if not exists severity text;
alter table audit_logs add column if not exists target_type text;
alter table audit_logs add column if not exists target_id uuid;
alter table audit_logs add column if not exists target_label text;
alter table audit_logs add column if not exists summary text;
alter table audit_logs add column if not exists details text;
alter table audit_logs add column if not exists metadata_json jsonb not null default '{}'::jsonb;

create table if not exists public_rate_limits (
  id bigint generated by default as identity primary key,
  scope text not null,
  key text not null,
  created_at timestamptz not null default now()
);

create table if not exists app_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null check (role in ('admin', 'attendant', 'viewer')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_registrations_cpf on registrations(cpf);
create index if not exists idx_registrations_status on registrations(status);
create index if not exists idx_registrations_patient_notified_at on registrations(patient_notified_at);
create index if not exists idx_registrations_picked_up_at on registrations(picked_up_at);
create index if not exists idx_registrations_last_accessed_at on registrations(last_accessed_at);
create index if not exists idx_registrations_deleted_at on registrations(deleted_at);
create index if not exists idx_logs_registration_id on audit_logs("registrationId");
create index if not exists idx_public_validations_status on public_validations(status);
create index if not exists idx_public_validations_signature on public_validations("visualSignature");
create index if not exists idx_public_validations_id_clean
  on public_validations ((replace(upper(id::text), '-', '')) text_pattern_ops);
create index if not exists idx_public_validations_sig_clean
  on public_validations ((upper(regexp_replace(coalesce("visualSignature", ''), '[^a-zA-Z0-9]', '', 'g'))));
create index if not exists idx_public_validations_deleted_at on public_validations(deleted_at);
create index if not exists idx_public_rate_limits_scope_key_created
  on public_rate_limits(scope, key, created_at desc);

create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  with resolved as (
    select coalesce(
      auth.jwt() ->> 'app_role',
      (
        select role
        from public.app_profiles
        where id = auth.uid()
        limit 1
      ),
      'viewer'
    ) as role
  )
  select case
    when role = 'admin' and coalesce(auth.jwt() ->> 'aal', '') <> 'aal2' then 'viewer'
    else role
  end
  from resolved;
$$;

grant execute on function public.current_app_role() to authenticated;

-- request_ip() trusts Supabase edge headers. Keep the database reachable only
-- through the managed Supabase API/proxy path; do not expose direct DB access.
create or replace function public.request_ip()
returns text
language sql
stable
security definer
set search_path = public
as $$
  with headers as (
    select coalesce(nullif(current_setting('request.headers', true), '')::jsonb, '{}'::jsonb) as value
  )
  select coalesce(
    nullif(trim(split_part(headers.value ->> 'x-forwarded-for', ',', 1)), ''),
    nullif(trim(headers.value ->> 'cf-connecting-ip'), ''),
    nullif(trim(headers.value ->> 'x-real-ip'), ''),
    'unknown'
  )
  from headers;
$$;

create or replace function public.check_rate_limit(p_scope text, p_limit int, p_window_seconds int)
returns boolean
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_key text := public.request_ip();
  v_window interval := make_interval(secs => greatest(p_window_seconds, 1));
  v_count int;
begin
  select count(*)
  into v_count
  from public.public_rate_limits
  where scope = p_scope
    and key = v_key
    and created_at >= now() - v_window;

  if v_count >= p_limit then
    return false;
  end if;

  insert into public.public_rate_limits(scope, key) values (p_scope, v_key);
  return true;
end;
$$;

create or replace function public.cleanup_public_rate_limits(p_older_than interval default interval '1 day')
returns integer
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_deleted integer;
begin
  delete from public.public_rate_limits
  where created_at < now() - p_older_than;

  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

do $do$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    execute $cron$
      select cron.unschedule(jobid)
      from cron.job
      where jobname in ('cipf_rate_limit_cleanup_hourly', 'cipf_rate_limit_cleanup_daily')
    $cron$;

    execute $cron$
      select cron.schedule(
        'cipf_rate_limit_cleanup_daily',
        '0 3 * * *',
        $$select public.cleanup_public_rate_limits(interval '1 day')$$
      )
    $cron$;
  end if;
end;
$do$;

revoke all on function public.request_ip() from public;
revoke all on function public.check_rate_limit(text, int, int) from public;
revoke all on function public.cleanup_public_rate_limits(interval) from public;

create or replace function public.log_audit_event(
  p_action text,
  p_registration_id uuid default null,
  p_reason text default null,
  p_event_code text default null,
  p_category text default null,
  p_severity text default null,
  p_target_type text default null,
  p_target_label text default null,
  p_summary text default null,
  p_details text default null,
  p_metadata_json jsonb default '{}'::jsonb
)
returns void
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_role text := public.current_app_role();
  v_user_name text;
  v_event_code text := left(trim(coalesce(p_event_code, 'system.legacy_event')), 120);
  v_category text := coalesce(nullif(trim(p_category), ''), 'system');
  v_severity text := coalesce(nullif(trim(p_severity), ''), 'info');
  v_target_type text := coalesce(nullif(trim(p_target_type), ''), case when p_registration_id is null then 'system' else 'registration' end);
  v_summary text := left(trim(coalesce(p_summary, p_action, 'Evento do sistema')), 160);
  v_details text := left(coalesce(p_details, p_reason, ''), 4000);
begin
  if auth.uid() is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if v_role not in ('admin', 'attendant', 'viewer') then
    raise exception 'FORBIDDEN';
  end if;

  select full_name
  into v_user_name
  from public.app_profiles
  where id = auth.uid()
  limit 1;

  insert into public.audit_logs(
    "registrationId",
    "userId",
    "userName",
    ip,
    timestamp,
    action,
    reason,
    event_code,
    category,
    severity,
    target_type,
    target_id,
    target_label,
    summary,
    details,
    metadata_json
  )
  values (
    p_registration_id,
    auth.uid()::text,
    coalesce(nullif(v_user_name, ''), nullif(auth.jwt() ->> 'email', ''), 'Usuario autenticado'),
    public.request_ip(),
    now(),
    left(trim(coalesce(p_action, 'Acao sem nome')), 120),
    left(coalesce(p_reason, v_details), 2000),
    v_event_code,
    v_category,
    v_severity,
    v_target_type,
    p_registration_id,
    nullif(left(coalesce(p_target_label, ''), 160), ''),
    v_summary,
    nullif(v_details, ''),
    coalesce(p_metadata_json, '{}'::jsonb)
  );
end;
$$;

revoke all on function public.log_audit_event(text, uuid, text, text, text, text, text, text, text, text, jsonb) from public;
grant execute on function public.log_audit_event(text, uuid, text, text, text, text, text, text, text, text, jsonb) to authenticated;

create or replace function public.audit_registration_changes()
returns trigger
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_registration_id uuid;
  v_action text := 'Cadastro ' || lower(tg_op);
  v_event_code text := 'registration.changed';
  v_summary text := 'Cadastro alterado automaticamente';
  v_user_name text;
  v_reason text := 'Auditoria automatica por trigger';
begin
  if tg_op = 'DELETE' then
    v_registration_id := old.id;
  else
    v_registration_id := new.id;
  end if;

  if tg_op = 'UPDATE' then
    if old.deleted_at is null and new.deleted_at is not null then
      v_event_code := 'registration.archived';
      v_summary := 'Registro arquivado por trigger';
      v_reason := 'Arquivamento logico';
    elsif old.status is distinct from new.status then
      v_event_code := case
        when new.status = 'approved' then 'registration.approved'
        when new.status = 'issued' then 'card.issued'
        when new.status = 'cancelled' then 'registration.cancelled'
        else 'registration.changed'
      end;
      v_summary := case
        when new.status = 'approved' then 'Cadastro aprovado por trigger'
        when new.status = 'issued' then 'Carteirinha emitida por trigger'
        when new.status = 'cancelled' then 'Carteirinha cancelada por trigger'
        else 'Cadastro alterado por trigger'
      end;
      v_reason := 'Status: ' || coalesce(old.status, '-') || ' -> ' || coalesce(new.status, '-');
    else
      v_event_code := 'registration.edited';
      v_summary := 'Cadastro editado por trigger';
    end if;
  elsif tg_op = 'INSERT' then
    v_event_code := 'registration.created';
    v_summary := 'Cadastro inserido por trigger';
  elsif tg_op = 'DELETE' then
    v_event_code := 'registration.archived';
    v_summary := 'Cadastro removido por trigger';
  end if;

  select full_name
  into v_user_name
  from public.app_profiles
  where id = auth.uid()
  limit 1;

  insert into public.audit_logs("registrationId", "userId", "userName", ip, timestamp, action, reason, event_code, category, severity, target_type, target_id, summary, details, metadata_json)
  values (
    v_registration_id,
    auth.uid()::text,
    coalesce(nullif(v_user_name, ''), nullif(auth.jwt() ->> 'email', ''), 'Banco de dados'),
    public.request_ip(),
    now(),
    v_action,
    v_reason,
    v_event_code,
    'registration',
    case when v_event_code in ('registration.archived', 'registration.cancelled') then 'warning' else 'info' end,
    'registration',
    v_registration_id,
    v_summary,
    v_reason,
    jsonb_build_object('source', 'trigger', 'operation', tg_op)
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists trigger_audit_registrations on public.registrations;
create trigger trigger_audit_registrations
after insert or update or delete on public.registrations
for each row execute function public.audit_registration_changes();

revoke all on function public.audit_registration_changes() from public;

create or replace function public.validate_cipf(p_id uuid, p_sig text)
returns table (
  id uuid,
  "fullName" text,
  "cpfMasked" text,
  "issueDate" text,
  "expiryDate" text,
  status text,
  "visualSignature" text,
  checksum text
)
language plpgsql
volatile
security definer
set search_path = public
as $$
begin
  if not public.check_rate_limit('validate_cipf', 5, 60) then
    raise exception 'RATE_LIMITED: muitas consultas. Tente novamente em 1 minuto.';
  end if;

  return query
  select
    pv.id,
    pv."fullName",
    pv."cpfMasked",
    pv."issueDate",
    pv."expiryDate",
    pv.status,
    pv."visualSignature",
    pv.checksum
  from public.public_validations pv
  where pv.id = p_id
    and upper(trim(pv."visualSignature")) = upper(trim(p_sig))
    and pv.deleted_at is null
    and pv.status = 'issued'
  limit 1;
end;
$$;

create or replace function public.validate_cipf_public(p_registry text, p_sig text)
returns table (
  id uuid,
  "fullName" text,
  "cpfMasked" text,
  "issueDate" text,
  "expiryDate" text,
  status text,
  "visualSignature" text,
  checksum text
)
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_registry text := trim(coalesce(p_registry, ''));
  v_registry_clean text := upper(regexp_replace(trim(coalesce(p_registry, '')), '[^a-zA-Z0-9]', '', 'g'));
  v_sig text := upper(regexp_replace(trim(coalesce(p_sig, '')), '[^a-zA-Z0-9]', '', 'g'));
begin
  if not public.check_rate_limit('validate_cipf_public', 5, 60) then
    raise exception 'RATE_LIMITED: muitas consultas. Tente novamente em 1 minuto.';
  end if;

  if length(v_registry_clean) < 6 or length(v_sig) < 6 then
    return;
  end if;

  if v_registry ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
    return query
    select
      pv.id,
      pv."fullName",
      pv."cpfMasked",
      pv."issueDate",
      pv."expiryDate",
      pv.status,
      pv."visualSignature",
      pv.checksum
    from public.public_validations pv
    where pv.id = v_registry::uuid
      and upper(regexp_replace(coalesce(pv."visualSignature", ''), '[^a-zA-Z0-9]', '', 'g')) = v_sig
      and pv.deleted_at is null
      and pv.status = 'issued'
    limit 1;
    return;
  end if;

  return query
  select
    pv.id,
    pv."fullName",
    pv."cpfMasked",
    pv."issueDate",
    pv."expiryDate",
    pv.status,
    pv."visualSignature",
    pv.checksum
  from public.public_validations pv
  where replace(upper(pv.id::text), '-', '') like v_registry_clean || '%'
    and upper(regexp_replace(coalesce(pv."visualSignature", ''), '[^a-zA-Z0-9]', '', 'g')) = v_sig
    and pv.deleted_at is null
    and pv.status = 'issued'
  order by pv."issueDate" desc
  limit 1;
end;
$$;

revoke all on function public.validate_cipf(uuid, text) from public;
grant execute on function public.validate_cipf(uuid, text) to anon, authenticated;
revoke all on function public.validate_cipf_public(text, text) from public;
grant execute on function public.validate_cipf_public(text, text) to anon, authenticated;

create or replace function public.admin_transition_registration(
  p_registration_id uuid,
  p_action text,
  p_reason text default null
)
returns public.registrations
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_action text := lower(trim(coalesce(p_action, '')));
  v_reason text := nullif(trim(coalesce(p_reason, '')), '');
  v_registration public.registrations%rowtype;
  v_issue_date text := to_char(current_date, 'DD/MM/YYYY');
  v_expiry_date text := to_char((current_date + interval '2 years')::date, 'DD/MM/YYYY');
begin
  if auth.uid() is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if public.current_app_role() <> 'admin' then
    raise exception 'FORBIDDEN';
  end if;

  select *
  into v_registration
  from public.registrations
  where id = p_registration_id
    and deleted_at is null
  limit 1;

  if not found then
    raise exception 'NOT_FOUND';
  end if;

  if v_action in ('cancel', 'renew', 'reissue', 'archive') and v_reason is null then
    raise exception 'REASON_REQUIRED';
  end if;

  case v_action
    when 'approve' then
      update public.registrations set status = 'approved' where id = p_registration_id;
      update public.public_validations set status = 'approved' where id = p_registration_id;
      update public.registration_index
      set status = 'approved', updated_at = now()
      where cpf = regexp_replace(coalesce(v_registration.cpf, ''), '\D', '', 'g');

      perform public.log_audit_event(
        p_action => 'Cadastro aprovado',
        p_registration_id => p_registration_id,
        p_reason => coalesce(v_reason, 'Cadastro aprovado para emissao administrativa'),
        p_event_code => 'registration.approved',
        p_category => 'workflow',
        p_severity => 'info',
        p_target_type => 'registration',
        p_target_label => v_registration."fullName",
        p_summary => 'Cadastro aprovado',
        p_details => coalesce(v_reason, 'Cadastro aprovado para emissao administrativa')
      );

    when 'issue' then
      if coalesce(v_registration.status, 'under_review') = 'approved' then
        update public.registrations
        set status = 'issued',
            "issueDate" = v_issue_date,
            "expiryDate" = v_expiry_date
        where id = p_registration_id;

        update public.public_validations
        set status = 'issued',
            "issueDate" = v_issue_date,
            "expiryDate" = v_expiry_date
        where id = p_registration_id;

        update public.registration_index
        set status = 'issued', updated_at = now()
        where cpf = regexp_replace(coalesce(v_registration.cpf, ''), '\D', '', 'g');

        perform public.log_audit_event(
          p_action => 'Carteirinha emitida',
          p_registration_id => p_registration_id,
          p_reason => coalesce(v_reason, 'Emissao administrativa para impressao'),
          p_event_code => 'card.issued',
          p_category => 'workflow',
          p_severity => 'sensitive',
          p_target_type => 'registration',
          p_target_label => v_registration."fullName",
          p_summary => 'Carteirinha emitida',
          p_details => coalesce(v_reason, 'Emissao administrativa para impressao')
        );
      else
        perform public.log_audit_event(
          p_action => 'Acesso a impressao',
          p_registration_id => p_registration_id,
          p_reason => 'Carteirinha ja emitida',
          p_event_code => 'card.print_accessed',
          p_category => 'workflow',
          p_severity => 'info',
          p_target_type => 'registration',
          p_target_label => v_registration."fullName",
          p_summary => 'Tela de impressao acessada',
          p_details => 'Carteirinha ja emitida'
        );
      end if;

    when 'cancel' then
      update public.registrations set status = 'cancelled' where id = p_registration_id;
      update public.public_validations set status = 'cancelled' where id = p_registration_id;
      update public.registration_index
      set status = 'cancelled', updated_at = now()
      where cpf = regexp_replace(coalesce(v_registration.cpf, ''), '\D', '', 'g');

      perform public.log_audit_event(
        p_action => 'Carteirinha cancelada',
        p_registration_id => p_registration_id,
        p_reason => v_reason,
        p_event_code => 'registration.cancelled',
        p_category => 'workflow',
        p_severity => 'sensitive',
        p_target_type => 'registration',
        p_target_label => v_registration."fullName",
        p_summary => 'Carteirinha cancelada',
        p_details => v_reason
      );

    when 'renew' then
      update public.registrations
      set status = 'approved',
          "issueDate" = v_issue_date,
          "expiryDate" = v_expiry_date
      where id = p_registration_id;

      update public.public_validations
      set status = 'approved',
          "issueDate" = v_issue_date,
          "expiryDate" = v_expiry_date
      where id = p_registration_id;

      update public.registration_index
      set status = 'approved', updated_at = now()
      where cpf = regexp_replace(coalesce(v_registration.cpf, ''), '\D', '', 'g');

      perform public.log_audit_event(
        p_action => 'Cadastro renovado',
        p_registration_id => p_registration_id,
        p_reason => v_reason,
        p_event_code => 'registration.renewed',
        p_category => 'workflow',
        p_severity => 'sensitive',
        p_target_type => 'registration',
        p_target_label => v_registration."fullName",
        p_summary => 'Cadastro renovado',
        p_details => v_reason || '; nova validade=' || v_expiry_date
      );

    when 'reissue' then
      perform public.log_audit_event(
        p_action => 'Segunda via registrada',
        p_registration_id => p_registration_id,
        p_reason => v_reason,
        p_event_code => 'card.reissued',
        p_category => 'workflow',
        p_severity => 'sensitive',
        p_target_type => 'registration',
        p_target_label => v_registration."fullName",
        p_summary => 'Segunda via registrada',
        p_details => v_reason
      );

    when 'archive' then
      update public.registrations set status = 'cancelled' where id = p_registration_id;
      update public.public_validations set status = 'cancelled' where id = p_registration_id;
      update public.registration_index
      set status = 'cancelled', updated_at = now()
      where cpf = regexp_replace(coalesce(v_registration.cpf, ''), '\D', '', 'g');

      perform public.log_audit_event(
        p_action => 'Cadastro arquivado',
        p_registration_id => p_registration_id,
        p_reason => v_reason,
        p_event_code => 'registration.archived',
        p_category => 'workflow',
        p_severity => 'sensitive',
        p_target_type => 'registration',
        p_target_label => v_registration."fullName",
        p_summary => 'Cadastro arquivado',
        p_details => v_reason
      );

    else
      raise exception 'UNSUPPORTED_ACTION';
  end case;

  select *
  into v_registration
  from public.registrations
  where id = p_registration_id
  limit 1;

  return v_registration;
end;
$$;

create or replace function public.admin_request_export(
  p_export_kind text,
  p_filters_json jsonb default '{}'::jsonb
)
returns void
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_kind text := lower(trim(coalesce(p_export_kind, 'dashboard_csv')));
  v_summary text;
  v_event_code text;
begin
  if auth.uid() is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if public.current_app_role() <> 'admin' then
    raise exception 'FORBIDDEN';
  end if;

  v_event_code := case v_kind
    when 'dashboard_pdf' then 'export.dashboard_pdf'
    when 'monthly_pdf' then 'export.monthly_pdf'
    when 'backup_json' then 'system.backup_downloaded'
    else 'export.dashboard_csv'
  end;

  v_summary := case v_kind
    when 'dashboard_pdf' then 'Exportacao PDF solicitada'
    when 'monthly_pdf' then 'Relatorio mensal solicitado'
    when 'backup_json' then 'Backup JSON solicitado'
    else 'Exportacao CSV solicitada'
  end;

  perform public.log_audit_event(
    p_action => v_summary,
    p_event_code => v_event_code,
    p_category => case when v_kind = 'backup_json' then 'system' else 'export' end,
    p_severity => 'sensitive',
    p_target_type => 'system',
    p_target_label => 'Exportacao administrativa',
    p_summary => v_summary,
    p_details => left(coalesce(p_filters_json::text, '{}'), 4000),
    p_metadata_json => jsonb_build_object('exportKind', v_kind, 'filters', coalesce(p_filters_json, '{}'::jsonb))
  );
end;
$$;

revoke all on function public.admin_transition_registration(uuid, text, text) from public;
grant execute on function public.admin_transition_registration(uuid, text, text) to authenticated;
revoke all on function public.admin_request_export(text, jsonb) from public;
grant execute on function public.admin_request_export(text, jsonb) to authenticated;

alter table registrations enable row level security;
alter table registration_index enable row level security;
alter table public_validations enable row level security;
alter table cipf_files enable row level security;
alter table cipf_file_chunks enable row level security;
alter table audit_logs enable row level security;
alter table public_rate_limits enable row level security;
alter table app_profiles enable row level security;

drop policy if exists all_registrations on registrations;
drop policy if exists all_registration_index on registration_index;
drop policy if exists read_public_validations on public_validations;
drop policy if exists all_cipf_files on cipf_files;
drop policy if exists all_cipf_file_chunks on cipf_file_chunks;
drop policy if exists all_audit_logs on audit_logs;
drop policy if exists no_public_rate_limit_access on public_rate_limits;
drop policy if exists own_profile_read on app_profiles;
drop policy if exists admin_profile_read on app_profiles;
drop policy if exists authenticated_read_registrations on registrations;
drop policy if exists attendant_write_registrations on registrations;
drop policy if exists attendant_update_registrations on registrations;
drop policy if exists admin_delete_registrations on registrations;
drop policy if exists authenticated_read_registration_index on registration_index;
drop policy if exists attendant_write_registration_index on registration_index;
drop policy if exists attendant_update_registration_index on registration_index;
drop policy if exists admin_delete_registration_index on registration_index;
drop policy if exists authenticated_read_public_validations on public_validations;
drop policy if exists attendant_write_public_validations on public_validations;
drop policy if exists attendant_update_public_validations on public_validations;
drop policy if exists admin_delete_public_validations on public_validations;
drop policy if exists authenticated_read_files on cipf_files;
drop policy if exists attendant_write_files on cipf_files;
drop policy if exists admin_delete_files on cipf_files;
drop policy if exists authenticated_read_file_chunks on cipf_file_chunks;
drop policy if exists attendant_write_file_chunks on cipf_file_chunks;
drop policy if exists admin_delete_file_chunks on cipf_file_chunks;
drop policy if exists authenticated_read_audit_logs on audit_logs;

revoke all on registrations from anon;
revoke all on registration_index from anon;
revoke all on public_validations from anon;
revoke all on cipf_files from anon;
revoke all on cipf_file_chunks from anon;
revoke all on audit_logs from anon;
revoke all on public_rate_limits from anon, authenticated;

create policy own_profile_read
on app_profiles for select to authenticated
using (id = auth.uid());

create policy admin_profile_read
on app_profiles for select to authenticated
using (public.current_app_role() = 'admin');

create policy authenticated_read_registrations
on registrations for select to authenticated
using (public.current_app_role() in ('admin', 'attendant') and deleted_at is null);

create policy attendant_write_registrations
on registrations for insert to authenticated
with check (public.current_app_role() in ('admin', 'attendant'));

create policy attendant_update_registrations
on registrations for update to authenticated
using (public.current_app_role() in ('admin', 'attendant'))
with check (public.current_app_role() in ('admin', 'attendant'));

create policy authenticated_read_registration_index
on registration_index for select to authenticated
using (public.current_app_role() in ('admin', 'attendant'));

create policy attendant_write_registration_index
on registration_index for insert to authenticated
with check (public.current_app_role() in ('admin', 'attendant'));

create policy attendant_update_registration_index
on registration_index for update to authenticated
using (public.current_app_role() in ('admin', 'attendant'))
with check (public.current_app_role() in ('admin', 'attendant'));

create policy admin_delete_registration_index
on registration_index for delete to authenticated
using (public.current_app_role() in ('admin', 'attendant'));

create policy authenticated_read_public_validations
on public_validations for select to authenticated
using (public.current_app_role() in ('admin', 'attendant') and deleted_at is null);

create policy attendant_write_public_validations
on public_validations for insert to authenticated
with check (public.current_app_role() in ('admin', 'attendant'));

create policy attendant_update_public_validations
on public_validations for update to authenticated
using (public.current_app_role() in ('admin', 'attendant'))
with check (public.current_app_role() in ('admin', 'attendant'));

create policy authenticated_read_files
on cipf_files for select to authenticated
using (public.current_app_role() in ('admin', 'attendant'));

create policy attendant_write_files
on cipf_files for insert to authenticated
with check (public.current_app_role() in ('admin', 'attendant'));

create policy admin_delete_files
on cipf_files for delete to authenticated
using (public.current_app_role() = 'admin');

create policy authenticated_read_file_chunks
on cipf_file_chunks for select to authenticated
using (public.current_app_role() in ('admin', 'attendant'));

create policy attendant_write_file_chunks
on cipf_file_chunks for insert to authenticated
with check (public.current_app_role() in ('admin', 'attendant'));

create policy admin_delete_file_chunks
on cipf_file_chunks for delete to authenticated
using (public.current_app_role() = 'admin');

create policy authenticated_read_audit_logs
on audit_logs for select to authenticated
using (public.current_app_role() = 'admin');

create policy no_public_rate_limit_access on public_rate_limits for all to anon using (false) with check (false);
